import { SystemTweak, TweakCategory } from './types.js';

/**
 * Registry of all available system tweaks and tools.
 */
export const TWEAK_REGISTRY: SystemTweak[] = [
  // ─── VISUALS ────────────────────────────────────────────────────────────────
  {
    id: 'dock-instant',
    name: 'Instant Dock',
    description: 'Removes the delay when the Dock auto-hides or shows.',
    category: TweakCategory.Visuals,
    applyCmd: '/usr/bin/defaults',
    applyArgs: ['write', 'com.apple.dock', 'autohide-delay', '-float', '0'],
    revertCmd: '/usr/bin/defaults',
    revertArgs: ['delete', 'com.apple.dock', 'autohide-delay'],
    stateCmd: '/usr/bin/defaults',
    stateArgs: ['read', 'com.apple.dock', 'autohide-delay'],
    appliedValue: '0',
    relaunchProcess: 'Dock',
    mechanism: 'Sets autohide-delay to 0 and restarts the Dock process.',
    requiresAdmin: false,
  },
  {
    id: 'dock-animation-speed',
    name: 'Fast Dock Animation',
    description: 'Makes the Dock sliding animation much faster.',
    category: TweakCategory.Visuals,
    applyCmd: '/usr/bin/defaults',
    applyArgs: ['write', 'com.apple.dock', 'autohide-time-modifier', '-float', '0.15'],
    revertCmd: '/usr/bin/defaults',
    revertArgs: ['delete', 'com.apple.dock', 'autohide-time-modifier'],
    stateCmd: '/usr/bin/defaults',
    stateArgs: ['read', 'com.apple.dock', 'autohide-time-modifier'],
    appliedValue: '0.15',
    relaunchProcess: 'Dock',
    mechanism: 'Sets autohide-time-modifier to 0.15 (default is ~1.0).',
    requiresAdmin: false,
  },
  {
    id: 'window-animations',
    name: 'Instant Windows',
    description: 'Disables smooth window opening/closing animations for speed.',
    category: TweakCategory.Visuals,
    applyCmd: '/usr/bin/defaults',
    applyArgs: ['write', 'NSGlobalDomain', 'NSAutomaticWindowAnimationsEnabled', '-bool', 'false'],
    revertCmd: '/usr/bin/defaults',
    revertArgs: ['write', 'NSGlobalDomain', 'NSAutomaticWindowAnimationsEnabled', '-bool', 'true'],
    stateCmd: '/usr/bin/defaults',
    stateArgs: ['read', 'NSGlobalDomain', 'NSAutomaticWindowAnimationsEnabled'],
    appliedValue: '0',
    mechanism: 'Sets NSAutomaticWindowAnimationsEnabled to false globally.',
    requiresAdmin: false,
  },
  {
    id: 'resize-animations',
    name: 'Instant Window Resize',
    description: 'Removes the delay when windows are being resized.',
    category: TweakCategory.Visuals,
    applyCmd: '/usr/bin/defaults',
    applyArgs: ['write', 'NSGlobalDomain', 'NSWindowResizeTime', '-float', '0.001'],
    revertCmd: '/usr/bin/defaults',
    revertArgs: ['delete', 'NSGlobalDomain', 'NSWindowResizeTime'],
    stateCmd: '/usr/bin/defaults',
    stateArgs: ['read', 'NSGlobalDomain', 'NSWindowResizeTime'],
    appliedValue: '0.001',
    mechanism: 'Sets NSWindowResizeTime to near-zero (default is 0.2).',
    requiresAdmin: false,
  },

  // ─── MAINTENANCE ────────────────────────────────────────────────────────────
  {
    id: 'ram-purge',
    name: 'Purge Memory (RAM)',
    description: 'Forces macOS to flush inactive memory and file system caches.',
    category: TweakCategory.Maintenance,
    applyCmd: '/usr/bin/purge',
    applyArgs: [],
    revertCmd: '', // One-off action
    revertArgs: [],
    stateCmd: '', // Always available
    stateArgs: [],
    appliedValue: '',
    mechanism: 'Executes "sudo purge" to reclaim RAM from inactive processes.',
    requiresAdmin: true,
  },
  {
    id: 'dns-flush',
    name: 'Flush DNS Cache',
    description: 'Clears the system DNS resolver cache to fix network hangups.',
    category: TweakCategory.Network,
    applyCmd: '/usr/bin/killall',
    applyArgs: ['-HUP', 'mDNSResponder'],
    revertCmd: '', // One-off action
    revertArgs: [],
    stateCmd: '',
    stateArgs: [],
    appliedValue: '',
    mechanism: 'Sends HUP signal to mDNSResponder to reset DNS cache.',
    requiresAdmin: true,
  },
  
  // ─── POWER ──────────────────────────────────────────────────────────────────
  {
    id: 'low-power-mode',
    name: 'Force Low Power Mode',
    description: 'Keeps CPU clock speeds lower to save battery and stay cool.',
    category: TweakCategory.Power,
    applyCmd: '/usr/bin/pmset',
    applyArgs: ['-a', 'lowpower', '1'],
    revertCmd: '/usr/bin/pmset',
    revertArgs: ['-a', 'lowpower', '0'],
    stateCmd: '/usr/bin/pmset',
    stateArgs: ['-g'],
    appliedValue: 'lowpower 1',
    mechanism: 'Uses pmset to force low power mode globally (all power sources).',
    requiresAdmin: true,
  },
];
